erp/urls.py
from django.conf.urls import url
from erp import views



app_name = 'erp'



urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^allParts/$', views.viewAllParts, name='viewAllParts'),
	url(r'^allSeals/$', views.viewSeals, name='viewSeals'),
	url(r'^addPart/$', views.addPart, name='addPart'),
	url(r'^editPart/(?P<part_id>\d+)/$', views.editPart, name='editPart'),
	url(r'^addSeal/$', views.addSeal, name='addSeal'),
	url(r'^viewSeal/(?P<seal_id>\d+)/addComponent/$', views.addComponentToSeal, name='addComponentToSeal'),
	url(r'^viewSeal/(?P<seal_id>\d+)/addServiceReport/$', views.addServiceReport, name='addServiceReport'),
	url(r'^downloadServiceReport/(?P<report_id>\d+)/$', views.exportReportAsPDF, name='exportReportAsPDF'),
	url(r'^viewSeal/(?P<seal_id>\d+)/checkComponentChange/(?P<change_id>\d+)/$', views.checkComponentChange, name='checkComponentChange'),
	url(r'^viewSeal/(?P<seal_id>\d+)/$', views.viewSeal, name='viewSeal'),
	url(r'^addCompany/$', views.addCompany, name='addCompany'),
	url(r'^company/(?P<company_id>\d+)/addVessel/$', views.addVessel, name='addVessel'),
	url(r'^addVesselCompany/$', views.addVesselCompany, name='addVesselCompany'),
	url(r'^addMechanic/$', views.addMechanic, name='addMechanic'),
	url(r'^addCategory/$', views.addCategory, name='addCategory'),
	url(r'^addMaterial/$', views.addMaterial, name='addMaterial'),
	url(r'^addContactPerson/$', views.addContactPerson, name='addContactPerson'),
	url(r'^editCompany/(?P<company_id>\d+)/$', views.editCompany, name='editCompany'),
	url(r'^editVessel/(?P<vessel_id>\d+)/$', views.editVessel, name='editVessel'),
	url(r'^editMechanic/(?P<mechanic_id>\d+)/$', views.editMechanic, name='editMechanic'),
	url(r'^editSeal/(?P<seal_id>\d+)/$', views.editSeal, name='editSeal'),
	url(r'^editMaterial/(?P<material_id>\d+)/$', views.editMaterial, name='editMaterial'),
	url(r'^editCategory/(?P<category_id>\d+)/$', views.editCategory, name='editCategory'),
	url(r'^editContactPerson/(?P<contact_id>\d+)/$', views.editContactPerson, name='editContactPerson'),
]

isah/urls.py
from django.conf.urls import url
from isah import views
from isah.models import Seal, SealType, SealSize, SealCompany, SealVessel, LS, ContactPerson, ServiceReport, SealPart

app_name='isah'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^seals/$', views.sealOverview, name='SealOverview'),
	url(r'^seals/(?P<pk>\d+)/$', views.SealDetail, name='SealDetail'),
	url(r'^seals/add/$', views.SealCreate, name="SealCreateForm"),
	url(r'^seals/(?P<pk>\d+)/edit/$', views.SealEdit, name='SealEditForm'),
	url(r'^seals/(?P<pk>\d+)/delete/$', views.Delete.as_view(model=Seal, template_name='isah/delete.html', success_url='/isah/seals/',extra_context={'title':'Delete seal ', 'submit':'Delete', 'cancel':'SealOverview'}), name='SealDeleteForm'),
        url(r'^seals/(?P<pk>\d+)/addpart/$', views.SealAddPart, name='SealAddPartForm'),
	url(r'^seals/(?P<pk>\d+)/part/(?P<part_id>\d+)/edit/$', views.SealPartEdit, name='SealPartEditForm'),
	url(r'^seals/(?P<pk>\d+)/part/(?P<part_id>\d+)/delete/$', views.Delete.as_view(model=SealPart, template_name='isah/delete.html', success_url='/isah/seals/',extra_context={'title':'Delete seal part', 'submit':'Delete', 'cancel':'SealOverview'}), name='SealPartDeleteForm'),
	url(r'^seals/sizes/$', views.SealSizeOverview, name='SealSizeOverview'),
	url(r'^seals/sizes/add/$', views.SealSizeCreate, name='SealSizeCreateForm'),
	url(r'^seals/sizes/(?P<pk>\d+)/edit/$', views.SealSizeEdit, name='SealSizeEditForm'),
	url(r'^seals/sizes/(?P<pk>\d+)/delete/$', views.Delete.as_view(model=SealSize, template_name='isah/delete.html', success_url='/isah/seals/sizes/',extra_context={'title':'Delete seal size', 'submit':'Delete', 'cancel':'SealSizeOverview'}), name='SealSizeDeleteForm'),
	url(r'^seals/types/$', views.SealTypeOverview, name='SealTypeOverview'),
	url(r'^seals/types/add/$', views.SealTypeCreate, name='SealTypeCreateForm'),
	url(r'^seals/types/(?P<pk>\d+)/edit/$', views.SealTypeEdit, name='SealTypeEditForm'),
	url(r'^seals/types/(?P<pk>\d+)/delete/$', views.Delete.as_view(model=SealType, template_name='isah/delete.html', success_url='/isah/seals/types/',extra_context={'title':'Delete seal type', 'submit':'Delete', 'cancel':'SealTypeOverview'}), name='SealTypeDeleteForm'),
	url(r'^companies/$', views.SealCompanyOverview, name='SealCompanyOverview'),
	url(r'^companies/(?P<pk>\d+)/$', views.SealCompanyDetail, name='SealCompanyDetail'),
	url(r'^companies/add/$', views.SealCompanyCreate, name='SealCompanyCreateForm'),
	url(r'^companies/(?P<pk>\d+)/edit/$', views.SealCompanyEdit, name='SealCompanyEditForm'),
	url(r'^companies/(?P<pk>\d+)/delete/$', views.Delete.as_view(model=SealCompany, template_name='isah/delete.html', success_url='/isah/companies/',extra_context={'title':'Delete company', 'submit':'Delete', 'cancel':'SealCompanyOverview'}), name='SealCompanyDeleteForm'),
	url(r'^vessels/$', views.SealVesselOverview, name='SealVesselOverview'),
	url(r'^vessels/(?P<pk>\d+)/$', views.SealVesselDetail, name='SealVesselDetail'),
	url(r'^vessels/add/$', views.SealVesselCreate, name='SealVesselCreateForm'),
	url(r'^vessels/(?P<pk>\d+)/edit/$', views.SealVesselEdit, name='SealVesselEditForm'),
	url(r'^vessels/(?P<pk>\d+)/delete/$', views.Delete.as_view(model=SealVessel, template_name='isah/delete.html', success_url='/isah/vessels/',extra_context={'title':'Delete vessel', 'submit':'Delete', 'cancel':'SealVesselOverview'}), name='SealVesselDeleteForm'),
	url(r'^ls/$', views.LSOverview, name='LSOverview'),
	url(r'^ls/(?P<pk>\d+)/$', views.LSDetail, name='LSDetail'),
	url(r'^ls/add/$', views.LSCreate, name='LSCreateForm'),
	url(r'^ls/(?P<pk>\d+)/edit/$', views.LSEdit, name='LSEditForm'),
	url(r'^ls/(?P<pk>\d+)/delete/$', views.Delete.as_view(model=LS, template_name='isah/delete.html', success_url='/isah/ls/',extra_context={'title':'LS number', 'submit':'Delete', 'cancel':'SealVesselOverview'}), name='LSDeleteForm'),
	url(r'^importcsv/$', views.importcsv, name='importcsv'),
	url(r'^contacts/$', views.ContactPersonOverview, name='ContactPersonOverview'),
	url(r'^contacts/(?P<pk>\d+)/$', views.ContactPersonDetail, name='ContactPersonDetail'),
	url(r'^contacts/add/$', views.ContactPersonCreate, name='ContactPersonCreateForm'),
	url(r'^contacts/(?P<pk>\d+)/edit/$', views.ContactPersonEdit, name='ContactPersonEditForm'),
	url(r'^contacts/(?P<pk>\d+)/delete/$', views.Delete.as_view(model=ContactPerson, template_name='isah/delete.html', success_url='/isah/contacts/',extra_context={'title':'Contact person', 'submit':'Delete', 'cancel':'ContactPersonOverview'}), name='ContactPersonDeleteForm'),
	url(r'^servicereport/$', views.ServiceReportOverview, name='ServiceReportOverview'),
	url(r'^servicereport/(?P<pk>\d+)/$', views.ServiceReportDetail, name='ServiceReportDetail'),
	url(r'^servicereport/add/(?P<pk>\d+)/$', views.ServiceReportCreate, name='ServiceReportLSCreateForm'),
	url(r'^servicereport/add/$', views.ServiceReportCreate, name='ServiceReportCreateForm'),
	url(r'^servicereport/(?P<pk>\d+)/edit/$', views.ServiceReportEdit, name='ServiceReportEditForm'),
	url(r'^servicereport/(?P<pk>\d+)/delete/$', views.Delete.as_view(model=ServiceReport, template_name='isah/delete.html', success_url='/isah/contacts/',extra_context={'title':'Service report', 'submit':'Delete', 'cancel':'ServiceReportOverview'}), name='ServiceReportDeleteForm'),
	url(r'^servicereport/(?P<pk>\d+)/export/$', views.exportReportAsPDF, name='exportReportAsPDF'),
	# start servicereport wizard
	url(r'^servicereport/select_ls/$', views.ServiceReportSelectLS, name='ServiceReportSelectLSForm'),
	url(r'^servicereport/(?P<pk>\d+)/general_info/$', views.ServiceReportGeneralInfo, name='ServiceReportGeneralInfoForm'),
	url(r'^servicereport/(?P<pk>\d+)/select_seals/$', views.ServiceReportSelectSeals, name='ServiceReportSelectSealsForm'),
]

lagersmit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ajax_select import urls as ajax_select_urls


from tastypie.api import Api
from angular.api import JobResource


job_resource = JobResource()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sealadvisor2/', include('sealadvisor2.urls')),
    url(r'^erp/', include('erp.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^isah/', include('isah.urls')),
    url(r'^servicerapportage/', include('servicerapportage.urls')),
    url(r'^api/', include(job_resource.urls)),
]

isah/models.py
from django.db import models
from sealadvisor2.models import AftSealOptions, FwdSealOptions

# Create your models here.


# overview of the model connections:
# 0: Seal (x-number)
# 1: Object (x-number): 
# 2: Vessel (IMO): 
# 3: Order (LS-number): 
# 4: Company



# Create your models here.





class SealCompany(models.Model):
    name = models.CharField(max_length=100, verbose_name="Name")

    # preferences for a company regarding the seal advisor
    aft_preferences = models.ForeignKey(AftSealOptions, on_delete=models.CASCADE)
    fwd_preferences = models.ForeignKey(FwdSealOptions, on_delete=models.CASCADE)


    street_and_number = models.CharField(max_length=100, null=True, blank=True, verbose_name="Address")
    postal_code = models.CharField(max_length=12, null=True, blank=True, verbose_name="Postal Code")
    province = models.CharField(max_length=100, null=True, blank=True, verbose_name="Province")
    city = models.CharField(max_length=100, null=True, blank=True, verbose_name="City")



    
    def __str__(self):
        return self.name


class SealVessel(models.Model):
    name = models.CharField(max_length=100, verbose_name="Name")
    company = models.ForeignKey(SealCompany, on_delete=models.CASCADE, verbose_name='Company')
    imo_number = models.CharField(max_length=10, verbose_name="IMO number")

    def __str__(self):
        return self.name


class ContactPerson(models.Model):
    company = models.ForeignKey(SealCompany, verbose_name='Company')
    first_name = models.CharField(max_length=100, verbose_name='First name')
    last_name = models.CharField(max_length=100, verbose_name='Last name')
    email = models.EmailField()
    position = models.CharField(max_length=100, verbose_name="Position")

    def __str__(self):
        return self.first_name + " " + self.last_name

class SealType(models.Model):
    name = models.CharField(max_length=10, help_text="Type such as 'STA'")
    description = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
class SealSize(models.Model):
    size = models.IntegerField()
    
    def __str__(self):
        return str(self.size)
    
class Part(models.Model):
    name = models.CharField(max_length=100, help_text="Part name")
    applicable_sizes = models.ManyToManyField(SealSize, verbose_name='Applicable sizes')

    def __str__(self):
        return self.name





class Seal(models.Model):
    seal_type = models.ForeignKey(SealType, verbose_name='Type')
    size = models.ForeignKey(SealSize, verbose_name='Size')

    CHOICES = (
        ('N/A', 'Not applicable'),
        ('PS', 'Port side'),
        ('SB', 'Starboard')
    )

    side = models.CharField(max_length=10, choices=CHOICES, verbose_name='Side', help_text='At which side is the seal installed or leave blank in case of a single propellor')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    updated = models.DateTimeField(auto_now=True, verbose_name='Last updated')
    serial_number = models.CharField(max_length=15, verbose_name= 'Serial number')
    company = models.ForeignKey(SealCompany, on_delete=models.CASCADE, verbose_name='Company')
    vessel = models.ForeignKey(SealVessel, on_delete=models.CASCADE, verbose_name='Vessel', null=True, blank=True)

    # parts list

    def __str__(self):
        return self.serial_number


class SealPart(models.Model):
    number_of_parts = models.IntegerField(verbose_name = "Number of this part in the seal")
    part = models.ForeignKey(Part, verbose_name = 'Part')

    CHOICES = (
            ('as_installed', 'As installed'),
            ('as_maintained', 'As maintained'),
    )

    status = models.CharField(verbose_name='Status', choices=CHOICES, max_length=20)
    seal = models.ForeignKey(Seal, verbose_name='Related seal')

    def __str__(self):
        return str("{number}x {part}").format(number = self.number_of_parts, part = self.part)




    
    
    
class LS(models.Model):
    LS_number = models.CharField(max_length=10, verbose_name='LS number')
    description = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Description')
    company = models.ForeignKey(SealCompany, verbose_name='Company')
    seals = models.ManyToManyField(Seal, verbose_name='Related seals', blank=True)

    def __str__(self):
        return self.LS_number


class ServiceReport(models.Model):
    ls = models.ForeignKey(LS, verbose_name='LS order no.')
    vessel = models.ForeignKey(SealVessel, verbose_name='Serviced vessel')
    superintendant = models.ForeignKey(ContactPerson, verbose_name='Contact person')
    date_from = models.DateField(verbose_name='Start date')
    date_to = models.DateField(verbose_name='End date')
    location = models.CharField(max_length=200, verbose_name='Location')
    remarks = models.CharField(max_length=2000, verbose_name='Remarks', blank=True, help_text='General (not related to a seal) remarks')

isah/forms.py
from django import forms
from isah.models import SealSize, SealType, Seal, SealCompany, SealVessel, LS, ContactPerson, ServiceReport, SealPart


class SealForm(forms.ModelForm):
    size = forms.ModelChoiceField(SealSize.objects.order_by('size'), required=True)

    class Meta:
        model = Seal
        fields = ('company', 'vessel', 'serial_number','seal_type','size')


class SealSizeForm(forms.ModelForm):


    def clean_size(self):
        size = self.cleaned_data['size']

        if self.instance.id:
            # if editing this form an instance id exist, so exlude the current instance:
            if SealSize.objects.filter(size = size).exclude(pk=self.instance.id).count() > 0: # check if other objects with the same value exist
                raise forms.ValidationError('Size does already exist, try a different size')

        else:
            # new instance, so no id yet:
            if SealSize.objects.filter(size = size).count() > 0:
                raise forms.ValidationError('Size does already exist, try a different size')

        return size


    class Meta:
        model = SealSize
        fields = ('size',)



class SealTypeForm(forms.ModelForm):

    def clean_name(self):
        name = self.cleaned_data['name']

        if self.instance.id:
            # if editing this form an instance id exist, so exlude the current instance:
            if SealType.objects.filter(name = name).exclude(pk=self.instance.id).count() > 0:
                raise forms.ValidationError('Name does already exist, try a different name')
        else:
            # new instance, so no id yet:
            if SealType.objects.filter(name = name).count() > 0:
                raise forms.ValidationError('Name does already exist, try a different name')

        return name

    class Meta:
        model = SealType
        fields = ('name','description')




class SealCompanyForm(forms.ModelForm):

    class Meta:
        model = SealCompany
        fields = ('name', 'street_and_number', 'postal_code','city', 'province' )



class SealVesselForm(forms.ModelForm):

    class Meta:
        model = SealVessel
        fields = ('name','company','imo_number')


class LSForm(forms.ModelForm):

    class Meta:
        model = LS
        fields = ('LS_number','description','company', 'seals')


class ContactPersonForm(forms.ModelForm):

    class Meta:
        model = ContactPerson
        fields = ('company', 'first_name', 'last_name', 'email', 'position')


class ServiceReportForm(forms.ModelForm):

    remarks = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = ServiceReport
        fields = ('ls', 'date_from', 'date_to', 'superintendant', 'location', 'remarks')


class ServiceReportSelectLSForm(forms.Form):

    CHOICES = [[ls.id, ls.LS_number] for ls in LS.objects.all()]
    CHOICES.insert(0,["-", "---Select---"])

    ls = forms.ChoiceField(choices=CHOICES, required=True, label='LS order no.')

    def clean_ls(self):
        ls = self.cleaned_data['ls']

        if not ls.isdigit():
            raise forms.ValidationError("Select a LS order no.")

        return ls

    class Meta:
        fields = ('ls', )


class ServiceReportGeneralInfoForm(forms.ModelForm):

    class Meta:
        model = ServiceReport
        fields = ('date_from', 'date_to', 'superintendant', 'vessel', 'location', 'remarks')
        widgets = {
            'date_from': forms.DateInput(attrs={'class':'datepicker'}),
        }

class ServiceReportSelectSealsForm(forms.ModelForm):

    class Meta:
        model = LS
        fields = ('seals', )


class SealAddPartForm(forms.ModelForm):

    class Meta:
        model = SealPart
        fields = ('number_of_parts','part','status')

isah/templates/isah/delete.html
{% extends 'isah/base.html' %}
{% load static %}
{% load material_form %} 


{% block content %}
<h1>Delete confirmation</h1>
<div class='row'>
	<div class='col s6'>
		<div class='card teal lighten-4'>
			<div class='card-content'>
				<span class='card-title black-text'>{{ title }}</span>
				<p>Are you sure you want to delete {{ object }}?</p>
				<form method="POST" class="post-form">
                    {% csrf_token %}
                    {% form form=form %} {% endform %}
                    <br>
                    <button type="submit" class="save btn btn-default">Delete</button>
                    <a href="{% url 'isah:'|add:cancel %}" class='btn waves-effect waves-light'>Cancel</a>
                </form>
			</div>
		</div>
	</div>
</div>


{% endblock %}

isah/templates/isah/ls.html
{% extends 'isah/base.html' %}
{% load static %}


{% block content %}
<h1>{{ vessel }}</h1>
<div class='row'>
    <div class='col s6'>
        <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>LS information</span>
                <div style='float:right;'>
                    <a class="btn-floating waves-effect waves-light blue" href="{% url 'isah:LSEditForm' ls.id %}?next={{request.path}}"><i class="material-icons">edit</i></a>
                </div>
                <table class='teal lighten-5' style='font-size:0.8em;'>
                    <tbody>
                        <tr>
                            <td>Name</td><td>{{ ls.LS_number }}</td>
                        </tr>
                        <tr>
                            <td>Description</td><td>{{ ls.description }}</td>
                        </tr>
                    </tbody>
                </table>    
            </div>
        </div>
    </div>
    <div class='col s6'>
        <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>Seals</span>
                {% for seal in seals %}
                    <p><a href="{% url 'isah:SealDetail' seal.id %}">{{ seal.serial_number }}</a></p>
                {% endfor %}
            </div>
        </div>
        <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>Service reports</span>
                <div style='float:right;'>
                    <a class="btn-floating waves-effect waves-light blue" href="{% url 'isah:ServiceReportLSCreateForm' ls.id %}?next={{request.path}}"><i class="material-icons">add</i></a>
                </div>
                {% for report in reports %}
                    <p><a href="{% url 'isah:ServiceReportDetail' report.id %}">{{ report.id }}</a></p>
                {% endfor %}
            </div>
        </div>

    </div>
</div>

{% endblock %}

isah/templates/isah/mainmenu.html
{% load static %}

<nav>
    <div class="nav-wrapper blue lighten-4">
    <a href="#" class="brand-logo"><img src="{% static 'images/logo-lagersmit.png' %}"></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'isah:index' %}">Home</a></li>
        <li><a href="{% url 'isah:SealOverview' %}">Seals</a></li>
        <li><a href="{% url 'isah:SealTypeOverview' %}">Seal types</a></li>
        <li><a href="{% url 'isah:SealSizeOverview' %}">Seal sizes</a></li>
        <li><a href="{% url 'isah:SealCompanyOverview' %}">Companies</a></li>
        <li><a href="{% url 'isah:SealVesselOverview' %}">Vessels</a></li>
        <li><a href="{% url 'isah:LSOverview' %}">LS numbers</a></li>
        <li><a href="{% url 'isah:ContactPersonOverview' %}">Contact persons</a></li>
        <li><a href="{% url 'isah:ServiceReportOverview' %}">Service reports</a></li>
    </ul>
    </div>
</nav>

isah/templates/isah/servicereport.html
{% extends 'isah/base.html' %}
{% load static %}


{% block content %}
<h1>Service report #{{ servicereport.id }} (<a href="{% url 'isah:exportReportAsPDF' servicereport.id %}">Download</a>)</h1>
<div class='row'>
    <div class='col s6'>
        <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>Service report information</span>
                <div style='float:right;'>
                    <a class="btn-floating waves-effect waves-light blue" href="{% url 'isah:ServiceReportEditForm' servicereport.id %}?next={{request.path}}"><i class="material-icons">edit</i></a>
                </div>
                <table class='teal lighten-5' style='font-size:0.8em;'>
                    <tbody>
                        <tr>
                            <td>LS order no.</td><td><a href="{% url 'isah:ServiceReportDetail' servicereport.id %}">{{ servicereport.ls }}</a></td>
                        </tr>
                        <tr>
                            <td>Date from</td><td>{{ servicereport.date_from }}</td>
                        </tr>
                        <tr>
                            <td>Date to</td><td>{{ servicereport.date_to }}</td>
                        </tr>
                        <tr>
                            <td>Superintendant</td><td>{{ servicereport.superintendant }}</td>
                        </tr>
                        <tr>
                            <td>Vessel</td><td>{{ servicereport.vessel }}</td>
                        </tr>
                        <tr>
                            <td>Location</td><td>{{ servicereport.location }}</td>
                        </tr>
                        <tr>
                            <td>Remarks</td><td>{{ servicereport.remarks }}</td>
                        </tr>
                    </tbody>
                </table>    
            </div>
        </div>
        <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>Company information</span>
                <div style='float:right;'>
                    <a class="btn-floating waves-effect waves-light blue" href="{% url 'isah:SealCompanyEditForm' servicereport.ls.company.id %}?next={{request.path}}"><i class="material-icons">edit</i></a>
                </div>
                <table class='teal lighten-5' style='font-size:0.8em;'>
                    <tbody>
                        <tr>
                            <td>Name</td><td><a href="{% url 'isah:SealCompanyDetail' servicereport.ls.company.id %}">{{ servicereport.ls.company.name }}</a></td>
                        </tr>
                        <tr>
                            <td>Address</td><td>{{ servicereport.ls.company.street_and_number }}</td>
                        </tr>
                        <tr>
                            <td>Postal code</td><td>{{ servicereport.ls.company.postal_code }}</td>
                        </tr>
                        <tr>
                            <td>Province</td><td>{{ servicereport.ls.company.province }}</td>
                        </tr>
                        <tr>
                            <td>City</td><td> {{ servicereport.ls.company.city }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class='col s6'>
        <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>Add seal</span>
                <div style='float:right;'>
                    <a class="btn-floating waves-effect waves-light blue" href="{% url 'isah:ServiceReportSelectSealsForm' servicereport.id %}?next={{request.path}}"><i class="material-icons">add</i></a>
                </div>
            </div>
        </div>
        {% for seal in servicereport.ls.seals.all %}
        <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>{{ seal.serial_number }} {% if "X" in seal.serial_number or 'x' in seal.serial_number %} (Aft seal) {% else %} (Fwd seal) {% endif %}</span>
                <div style='float:right;'>
                    <a class="btn-floating waves-effect waves-light blue" href="{% url 'isah:SealEditForm' seal.id %}?next={{request.path}}"><i class="material-icons">edit</i></a>
                </div>
                <table class='teal lighten-5' style='font-size:0.8em;'>
                    <tbody>
                            <td>Serial number</td><td><a href="{% url 'isah:SealDetail' seal.id %}">{{ seal.serial_number }}</a>{% if "X" in seal.serial_number or 'x' in seal.serial_number %} (Aft seal) {% else %} (Fwd seal) {% endif %}</td>
                        </tr>
                        <tr>
                            <td>Seal type</td><td>{{ seal.seal_type }}</td>
                        </tr>
                        <tr>
                            <td>Size</td><td>{{ seal.size }}</td>
                        </tr>
                        <tr>
                            <td>Created</td><td>{{ seal.created }}</td>
                        </tr>
                        <tr>
                            <td>Last updated</td><td> {{ seal.updated }}</td>
                        </tr>
                        <tr>
                            <td>Vessel</td><td>
                                {% if seal.vessel %}
                                    <a href="{% url 'isah:SealVesselDetail' seal.vessel.id %}">{{ seal.vessel }}</a>
                                    {% if seal.vessel != servicereport.vessel %}
                                        <b> > Different vessel from the vessel listed in the service report general information. Change this seal to vessel {{ servicereport.vessel }}?</b>
                                    {% endif %}
                                {% else %}
                                    No vessel listed
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

isah/templates/isah/simple_overview.html
{% extends 'isah/base.html' %}
{% load static %}


{% block content %}
<h1>{{ title }}</h1>

<div class="fixed-action-btn" style="bottom: 24px; right: 24px;">
	<a class="btn-floating btn-large red" href="{% url 'isah:SealSizeCreateForm' %}"><i class="large material-icons">add</i></a>
</div>


<div class='row'>
	<div class='col s6'>
		<div class='card teal lighten-4'>
			<div class='card-content'>
				<!--<span class='card-title black-text'>Add item</span>-->
				{% for size in sizes %}
				<p><a href="{% url 'isah:SealSizeEditForm' size.id %}">{{ size }}</a></p>
				{% endfor %}				
			</div>
		</div>
	</div>
</div>
{% endblock %}