erp/urls.py
from django.conf.urls import url
from erp import views



app_name = 'erp'



urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^allParts/$', views.viewAllParts, name='viewAllParts'),
	url(r'^allSeals/$', views.viewSeals, name='viewSeals'),
	url(r'^addPart/$', views.addPart, name='addPart'),
	url(r'^editPart/(?P<part_id>\d+)/$', views.editPart, name='editPart'),
	url(r'^addSeal/$', views.addSeal, name='addSeal'),
	url(r'^viewSeal/(?P<seal_id>\d+)/addComponent/$', views.addComponentToSeal, name='addComponentToSeal'),
	url(r'^viewSeal/(?P<seal_id>\d+)/addServiceReport/$', views.addServiceReport, name='addServiceReport'),
	url(r'^downloadServiceReport/(?P<report_id>\d+)/$', views.exportReportAsPDF, name='exportReportAsPDF'),
	url(r'^viewSeal/(?P<seal_id>\d+)/checkComponentChange/(?P<change_id>\d+)/$', views.checkComponentChange, name='checkComponentChange'),
	url(r'^viewSeal/(?P<seal_id>\d+)/$', views.viewSeal, name='viewSeal'),
	url(r'^addCompany/$', views.addCompany, name='addCompany'),
	url(r'^company/(?P<company_id>\d+)/addVessel/$', views.addVessel, name='addVessel'),
	url(r'^addVesselCompany/$', views.addVesselCompany, name='addVesselCompany'),
	url(r'^addMechanic/$', views.addMechanic, name='addMechanic'),
	url(r'^addCategory/$', views.addCategory, name='addCategory'),
	url(r'^addMaterial/$', views.addMaterial, name='addMaterial'),
	url(r'^addContactPerson/$', views.addContactPerson, name='addContactPerson'),
	url(r'^editCompany/(?P<company_id>\d+)/$', views.editCompany, name='editCompany'),
	url(r'^editVessel/(?P<vessel_id>\d+)/$', views.editVessel, name='editVessel'),
	url(r'^editMechanic/(?P<mechanic_id>\d+)/$', views.editMechanic, name='editMechanic'),
	url(r'^editSeal/(?P<seal_id>\d+)/$', views.editSeal, name='editSeal'),
	url(r'^editMaterial/(?P<material_id>\d+)/$', views.editMaterial, name='editMaterial'),
	url(r'^editCategory/(?P<category_id>\d+)/$', views.editCategory, name='editCategory'),
	url(r'^editContactPerson/(?P<contact_id>\d+)/$', views.editContactPerson, name='editContactPerson'),
]

lagersmit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ajax_select import urls as ajax_select_urls


from tastypie.api import Api
from angular.api import JobResource


job_resource = JobResource()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sealadvisor2/', include('sealadvisor2.urls')),
    url(r'^erp/', include('erp.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^isah/', include('isah.urls')),
    url(r'^servicerapportage/', include('servicerapportage.urls')),
    url(r'^api/', include(job_resource.urls)),
]

sealadvisor2/urls.py
from django.conf.urls import url
from sealadvisor2 import views
from erp.models import Company
from ajax_select import urls as ajax_select_urls


app_name = 'sealadvisor2'



urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^supreme/$', views.supreme, name='supreme'),
	url(r'^supreme/chooseSalesType/$', views.salesType, name='supremeSalesType'),
	url(r'^supreme/(?P<supreme_id>\d+)/edit/$', views.supremeEdit, name='supremeEdit'),
	url(r'^supreme/(?P<supreme_id>\d+)/aft/$', views.supremeAft, name='supremeAft'),
	url(r'^supreme/(?P<supreme_id>\d+)/fwd/$', views.supremeFwd, name='supremeFwd'),
	url(r'^supreme/(?P<supreme_id>\d+)/aft/(?P<aft_id>\d+)/edit$', views.supremeAftEdit, name='supremeAftEdit'),
	url(r'^supreme/(?P<supreme_id>\d+)/fwd/(?P<fwd_id>\d+)/edit$', views.supremeFwdEdit, name='supremeFwdEdit'),
	url(r'^supreme/(?P<supreme_id>\d+)/environment/$', views.supremeEnvironment, name='supremeEnvironment'),
	url(r'^supreme/(?P<supreme_id>\d+)/environment/(?P<env_id>\d+)/edit$', views.supremeEnvironmentEdit, name='supremeEnvironmentEdit'),
	url(r'^supreme/(?P<supreme_id>\d+)/overview/$', views.supremeOverview, name='supremeOverview'),
	url(r'^addcompany/$', views.CompanyCreate.as_view(), name="createCompany"),
	url(r'^updatecompany/(?P<pk>\d+)$', views.CompanyUpdate.as_view(success_url='/sealadvisor2/'), name="updateCompany"),
	url(r'^deletecompany/(?P<pk>\d+)$', views.CompanyDelete.as_view(success_url='/sealadvisor2/'), name="deleteCompany"),
	url(r'^deleteadvise/(?P<pk>\d+)$', views.AdviseDelete.as_view(success_url='/sealadvisor2/advises/'), name="deleteAdvise"),
	url(r'^companies/$', views.Companies, name='companies'),
	url(r'^advises/$', views.SupremeAdvises, name='advises'),
	url(r'^addtypeapproval/$', views.TypeApprovalCreate.as_view(success_url='/sealadvisor2/typeapprovals/'), name="createTypeApproval"),
	url(r'^updatetypeapproval/(?P<pk>\d+)$', views.TypeApprovalUpdate.as_view(success_url='/sealadvisor2/typeapprovals/'), name="updateTypeApproval"),
	url(r'^deletetypeapproval/(?P<pk>\d+)$', views.TypeApprovalDelete.as_view(success_url='/sealadvisor2/typeapprovals/'), name="deleteTypeApproval"),
	url(r'^typeapprovals/$', views.TypeApprovalOverview, name='typeApprovalOverview'),
	url(r'^addclass/$', views.ClassCreate.as_view(success_url='/sealadvisor2/class/'), name="createClass"),
	url(r'^updateclass/(?P<pk>\d+)$', views.ClassUpdate.as_view(success_url='/sealadvisor2/class/'), name="updateClass"),
	url(r'^deleteclass/(?P<pk>\d+)$', views.ClassDelete.as_view(success_url='/sealadvisor2/class/'), name="deleteClass"),
	url(r'^class/$', views.ClassOverview, name='classOverview'),
	#api urls
	url(r'^get_companies/$', views.get_companies, name='get_companies'),
	url(r'^companyEdit2/(?P<company_id>\d+)/$', views.CompanyDefaultsEdit, name='CompanyEdit2'),


]

sealadvisor2/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class sealApplication(models.Model):
    name = models.CharField(max_length=100)
    key = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Class(models.Model):
    key = models.CharField(max_length=10)

    className = models.CharField(max_length=100, verbose_name='Class')
    certificateNo = models.CharField(max_length=100, verbose_name='Certificate No.')

    def __str__(self):
        return str("{className} - {certificateNo}").format(className=self.className, certificateNo=self.certificateNo)


class Certificate(models.Model):
    key = models.CharField(max_length=10)

    bureau = models.CharField(max_length=100, verbose_name='Classification bureau')

    def __str__(self):
        return str("{bureau}").format(bureau=self.bureau)


class FwdSealOptions(models.Model):
    ocr = models.BooleanField(default=False, verbose_name='OCR ring')
    fkm = models.BooleanField(default=False, verbose_name='FKM lip-seals')
    hml = models.BooleanField(default = False, verbose_name='Hard metal layer (HML)')
    high_pressure = models.BooleanField(default=False, verbose_name= 'High pressure (3 lip-seals)')


class AftSealOptions(models.Model):
    seaguard = models.BooleanField(default=False, verbose_name='Seaguard (backup oil repellant lip-seal)')



    oring = models.BooleanField(default = False, verbose_name='O-ring between liner and shaft')
    anode = models.BooleanField(default = False, verbose_name='Cathodic protection')
    distanceRing = models.BooleanField(default = False, verbose_name='Distance ring')
    dirtBarrier = models.BooleanField(default = False, verbose_name='Dirt barrier')
    wireWinders = models.BooleanField(default = False, verbose_name='Wire winders')
    netCutters = models.BooleanField(default = False, verbose_name='Net cutters')
    hastelloy = models.BooleanField(default = False, verbose_name='Hastelloy springs')
    hml = models.BooleanField(default = False, verbose_name='Hard metal layer (HML)')
    air = models.BooleanField(default = False, verbose_name='Ventus/Athmos (depending on draught)')
    fkm = models.BooleanField(default=False, verbose_name='FKM lip-seals')


class environmentalOptions(models.Model):
    vgp = models.BooleanField(default=False, verbose_name='Has to comply with VGP regulations')

    OIL_CHOICES = (
        ('mineral', 'Mineral oil'),
        ('eal', 'EAL oil (bio degradable oil)'),
    )

    oil = models.CharField(max_length=20, choices=OIL_CHOICES, verbose_name='What kind of oil is used')

    oilType = models.CharField(max_length=100, verbose_name='What type of oil is used', blank=True, null=True)

    air = models.BooleanField(default = False, verbose_name='Use an air type system (Ventus/Athmos) to comply with VGP and reduce the pressure on the lip seals (only aft seal)')




from erp.models import Company


class supremeAdvise(models.Model):
    
    # for which company is the request?
    company = models.ForeignKey(Company)

    # first ask for general information 
    application = models.ForeignKey(sealApplication)

    CHOICES = (
        ('fpp', 'Fixed pitch'),
        ('cpp', 'Controllable pitch')
    )

    cpp_fpp = models.CharField(max_length=10,choices=CHOICES,verbose_name='Fixed or controllable pitch propellor', blank=True, null=True)

    number_of_shafts = models.IntegerField(verbose_name='Number of shafts per vessel')

    pressure_oring = models.BooleanField(default=False, verbose_name='Pressure O-ring')

    # in case that application is equal to 'sterntube', both the forward and/or aft seal required

    fwd_seal = models.BooleanField(default=False, verbose_name='Forward seal')
    aft_seal = models.BooleanField(default=False, verbose_name='Aft seal')

    vgp = models.BooleanField(default=False, verbose_name='Has to comply with VGP regulations')

    aft_build_in_length = models.DecimalField(max_digits=5, decimal_places=0, verbose_name='Aft seal build in length [mm]', blank=True, null=True)

    aftSize = models.DecimalField(max_digits=5, decimal_places=0,verbose_name='Aft shaft diameter (mm)', blank=True, null=True)
    fwdSize = models.DecimalField(max_digits=5, decimal_places=0,verbose_name='Forward shaft diameter (mm)', blank=True, null=True)

    rpm = models.DecimalField(max_digits=4, decimal_places=0, verbose_name = 'RPM')
    draught_shaft = models.DecimalField(max_digits=5, decimal_places=1, verbose_name='Draught to (aft) shaft centerline [m]')

    CHOICES = (
        ('shaft', 'Shaft centered'),
        ('hub', 'Hub centered'),
    )
    linerCentering = models.CharField(choices=CHOICES, max_length=20, verbose_name='Liner centering')

    aft = models.ForeignKey(AftSealOptions, null=True, blank=True)
    fwd = models.ForeignKey(FwdSealOptions, null=True, blank=True)
    environment = models.ForeignKey(environmentalOptions, null=True, blank=True)


    typeApproval = models.ForeignKey(Class, verbose_name='Type approval required (specify which or leave blank)', blank=True, null=True)
    classCertificate = models.ForeignKey(Certificate, verbose_name='Class certificate (specify which or leave blank)', blank=True, null=True)


    def __str__(self):
        return str("Advise {id} - {application}").format(id=self.id, application=self.application)

sealadvisor2/forms.py
from django import forms
from sealadvisor2.models import sealApplication, supremeAdvise, AftSealOptions, environmentalOptions,FwdSealOptions, Certificate
from erp.models import Company


class supremeSalesTypeForm(forms.Form):
	CHOICES = (
		('new','Supreme new'),
		('retrofit', 'Supreme retrofit'),
		('spares', 'Supreme spare parts')
	)

	sales_type = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
	# company1 = forms.ModelChoiceField(queryset=Company.objects.all(), label='Customer', required=False)
	# company = forms.CharField(max_length=100)


	def clean_sales_type(self):

		sales_type = self.cleaned_data['sales_type']

		if sales_type == 'spares' or sales_type == 'retrofit':
			raise forms.ValidationError('No spare parts or retrofit wizard yet')

		return sales_type

	class Meta:
		fields = ('sales_type', )


class supremeWizard(forms.ModelForm):
	# is the code below required?
	# def __init__(self, *args, **kwargs):
	# 	self._aft_seal = kwargs.pop('aft_seal', None)
	# 	self._fwd_seal = kwargs.pop('fwd_seal', None)
	# 	super(supremeWizard, self).__init__(*args, **kwargs)

	company_autocomplete = forms.CharField(max_length=100, label='Company')
	error_css_class = 'error'


	def clean_aftSize(self):
		aftSize = self.cleaned_data['aftSize']
		aft_seal = self.cleaned_data.get('aft_seal')

		if aft_seal:
			if aftSize is not None:
				if aftSize > 900 or aftSize < 90:
					raise forms.ValidationError("Size must be between 90 and 900")
			else:
				raise forms.ValidationError('Size is required')
		
		return aftSize

	def clean_fwdSize(self):
		fwdSize = self.cleaned_data['fwdSize']
		fwd_seal = self.cleaned_data.get('fwd_seal')

		if fwd_seal:
			if fwdSize is not None:
				if fwdSize > 900 or fwdSize < 90:
					raise forms.ValidationError("Size must be between 90 and 900")
			else:
				raise forms.ValidationError('Size is required')
		
		return fwdSize


	def clean_aft_build_in_length(self):
		aft_build_in_length = self.cleaned_data['aft_build_in_length']

		aft_seal = self.cleaned_data.get('aft_seal')

		if aft_seal:
			if aft_build_in_length is not None:
				if aft_build_in_length < 100 or aft_build_in_length > 1000:
					raise forms.ValidationError('Built in length must be between 100 and 1000 mm')

		return aft_build_in_length

	def clean_rpm(self):
		rpm = self.cleaned_data['rpm']

		if ( rpm > 500 or rpm < 80 ):
			raise forms.ValidationError("RPM must be between 80 and 500")
		return rpm

	CHOICES = (
		('shaft', 'Shaft centered'),
		('hub', 'Hub centered'),
	)

	linerCentering = forms.ChoiceField(choices=CHOICES)

	class Meta:
		model = supremeAdvise
		fields = ('company_autocomplete', 'application','cpp_fpp','number_of_shafts', 'vgp', 'aft_seal','linerCentering', 'aftSize','aft_build_in_length','fwd_seal','fwdSize','rpm', 'draught_shaft','typeApproval','classCertificate')


class supremeAftForm(forms.ModelForm):

	class Meta:
		model = AftSealOptions
		fields = ( 'seaguard', 'air', 'dirtBarrier','wireWinders','netCutters','oring', 'anode', 'hml', 'distanceRing','fkm','hastelloy')

class supremeFwdForm(forms.ModelForm):
	class Meta:
		model = FwdSealOptions
		fields = ('ocr', 'fkm','hml','high_pressure' )




		

class supremeEnvironmentForm(forms.ModelForm):
	OIL_CHOICES = (
		('mineral', 'Mineral oil'),
		('eal', 'EAL oil (bio degradable oil)'),
	)

	oil = forms.ChoiceField(widget=forms.RadioSelect, choices=OIL_CHOICES)

	class Meta:
		model = environmentalOptions
		fields = ('oil','oilType','vgp','air')



class CompanyEditForm(forms.ModelForm):

	class Meta:
		model = Company
		fields = ('name', )	

sealadvisor2/templates/sealadvisor2/add_supreme.html
{% extends 'sealadvisor2/base.html' %}
{% load static %}
{% load material_form %} 			

{% block content %}
<h1>Supreme Seal Advisor</h1>
<div class='row'>
	<div class='col s6'>
		<div class='card teal lighten-4'>
			<div class='card-content'>
				<span class='card-title black-text'>{{ title }}</span>
				<form method="POST" class="post-form">
                    {% csrf_token %}
                    {% form form=form %} {% endform %}

                    <br>
                    <button type="submit" class="save btn btn-default">{{ submit }}</button>
                    <a class='wave-effect btn' href="{% url 'sealadvisor2:index' %}">Cancel</a>
                </form>
			</div>
		</div>
	</div>
	<div class='col s6'>
	   <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>Extra information</span>
                <p id='pv_value'></p><br>
                <div id='fkm_card'>
                    <p>For a PV-value higher than 4 lagersmit requires FKM lip-seals to be used.</p><br>
                </div>
                <div id='ventus_card'>
                    <p>For a PV-value higher than 6 a ventus will be autoselected. This can be turned off later on if the customer does not want a ventus system.</p>
                    <p><img height='200px' src="{% static 'images/ventus.jpg' %}"></p><br>
                </div>
            </div>
        </div>	
	</div>

</div>

<script type='text/javascript'>
(function($) {
    $(function() {
        var selectField = $('#id_application');
        var fwd = $('#id_fwd_seal');
        var aft = $('#id_aft_seal');
        var aftsize = $('#id_aftSize');
        var fwdsize = $('#id_fwdSize');
        var fwdbuild = $('#id_fwd_build_in_length');
        var aftbuild = $('#id_aft_build_in_length');

        function toggleVerified(value) {
            value == '1' ? aft.parent().show() : aft.parent().hide();
            value == '1' ? fwd.parent().show() : fwd.parent().hide();
            toggleSizes();
        }

        function toggleSizes() {
            if (aft.is(':checked') || selectField.val() != '1') {
                aftsize.parent().show();
                aftbuild.parent().show();
            } else {
                aftsize.parent().hide(); 
                aftbuild.parent().show();
            }

            if (fwd.is(':checked')) {
                fwdsize.parent().show();
                fwdbuild.parent().show();
            } else {
                fwdsize.parent().hide();
                fwdbuild.parent().hide();
            }
        }




        function checkVentus(PV) {
            if ( $('#id_aftSize').val() > 0 && $('#id_rpm').val() && $('#id_draught_shaft').val() ) {
                PV = $('#id_aftSize').val()*3.14*($('#id_rpm').val()/60)*($('#id_draught_shaft').val()/10000);

                
            } else {
                PV = 0;
            }

            (PV > 6) ? $('#ventus_card').show() : $('#ventus_card').hide();
            (PV > 4) ? $('#fkm_card').show() : $('#fkm_card').hide();
            $('#pv_value').html("The PV-value is equal to " + PV.toFixed(1));
        }


        toggleSizes();
        checkVentus();


        $('#id_aftSize').keyup(function() {
            checkVentus();
        })

        $('#id_rpm').keyup(function() {
            checkVentus();
        })

        $('#id_draught_shaft').keyup(function() {
            checkVentus();
        })

        // show/hide on load based on pervious value of selectField
        toggleVerified(selectField.val());


        aft.change(function() {
            toggleSizes();
        })

        fwd.change(function() {
            toggleSizes();
        })

        // show/hide on change
        selectField.change(function() {
            toggleVerified($(this).val());
        });



        
    });
})(jQuery);

</script>
{% endblock %}	 

sealadvisor2/templates/sealadvisor2/advises.html
{% extends 'sealadvisor2/base.html' %}
{% load static %}
{% load material_form %} 			

{% block content %}
<h1>{{ title }}</h1>



<div class='row'>
	<div class='col s4'>
		<div class='card teal lighten-4'>
			<div class='card-content'>
				<span class='card-title black-text'>{{ title }}</span>
                {% for advise in advises %}
                    <p>{{ advise.company }}: <a href="{% url 'sealadvisor2:supremeOverview' advise.id %}">{{ advise }}</a> - <a href="{% url 'sealadvisor2:deleteAdvise' advise.id %}">(delete)</a></p>
                {% endfor %}
			</div>
		</div>
	</div>
	<div class='col s8'>

        

	</div>

</div>




{% endblock %}	 

sealadvisor2/templates/sealadvisor2/certificates.html
{% extends 'sealadvisor2/base.html' %}
{% load static %}
{% load material_form %} 			

{% block content %}
<h1>Certificates</h1>



<div class='row'>
	<div class='col s4'>
		<div class='card teal lighten-4'>
			<div class='card-content'>
                <div style='float:right;'>
                    <a class="btn-floating waves-effect waves-light blue" href="{% url 'sealadvisor2:createClass' %}"><i class="material-icons">add</i></a>
                </div>
				<span class='card-title black-text'>Certificates</span>
                {% for certificate in certificates %}
                    <p><a href="{% url 'sealadvisor2:updateClass' certificate.id %}">{{ certificate }}</a> - <a href="{% url 'sealadvisor2:deleteClass' certificate.id %}">(delete)</a></p>
                {% endfor %}
			</div>
		</div>
	</div>
	<div class='col s8'>

        

	</div>

</div>




{% endblock %}	 

sealadvisor2/templates/sealadvisor2/seal_information.html
{% extends 'sealadvisor2/base.html' %}
{% load static %}
{% load material_form %} 			

{% block content %}
<h1>Supreme Seal Advisor</h1>

{% for tab in tabs %}
<a href='{{ tab.href }}' class='btn waves-effect waves-light teal'>{{ tab.key }}</a>
{% endfor %}

<div class='row'>
	<div class='col s6'>
		<div class='card teal lighten-4'>
			<div class='card-content'>
				<span class='card-title black-text'>{{ title }}</span>
				<form method="POST" class="post-form">
                    {% csrf_token %}
                    {% form form=form %} {% endform %}
                    <br>
                    <br>
                    <button type="submit" class="save btn btn-default">{{ submit }}</button>
                    <!--<a class='wave-effect btn' href="{% url 'sealadvisor2:index' %}">Cancel</a>-->
                </form>
			</div>
		</div>
	</div>
	<div class='col s6'>

        <div class='card teal lighten-4' id='id_fpp_cpp_info'>
            <div class='card-content'>
                <span class='card-title black-text'>Fixed or controllable pitch</span>
                <p>A Controllable pitch propellor (CPP) has blades that can be adjusted to vary the thrust power or direction. When a CPP is used, the shaft has to be pulled to install the seal or a new liner.</p>
                <br>
                <p>When using a fixed pitch propellor, the aft seal can be installed without pulling the shaft as removal of the propellor is enough.</p>
                <br>
                <p align='center'><img height='200px' src="{% static 'images/cppfpp.jpg' %}">
            </div>
        </div>
        <div class='card teal lighten-4' id='id_vgp_info'>
            <div class='card-content'>
                <span class='card-title black-text'>VGP (Vessel general permit)</span>
                <p>The VGP states that no mineral oil can be leaked or a specific bio-oil must be used. To comply with the VGP regulations, either bio-oil must be used or an air type (Ventus/Athmos) seal must be used.</p>
                <br>
                
                <p>- Where does the vessel sail?</p>
                <p>- Does the vessel have to comply with the VGP for American waters?</p>
                
            </div>
        </div>
        
      <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>Explanation</span>
                
                <p><b>Shaft draught</b></p>
                <p>- What is the draught to the centerline of the shaft in loaded condition?</p>
            </div>
        </div>


        {% if air %}
		<div class='card teal lighten-4' id='air_card'>
			<div class='card-content'>
				<span class='card-title black-text'>Air type</span>
				<p>An air type system complies with VGP regulations and reduces the pressure on the lip-seals.</p>
				<br>
				<p>The PV-value is equal to: {{ pv }}</p>
				<p id='air_type'>For the specified draught a {{ air_type }} system is used.</p>
			</div>
		</div>
        {% endif %}
        {% if extra %}
        <div class='card teal lighten-4'>
            <div class='card-content'>
                <span class='card-title black-text'>Extra information</span>
                <p id='pv_value'></p><br>
                <div id='fkm_card'>
                    <p>For a PV-value higher than 4 lagersmit requires FKM lip-seals to be used.</p><br>
                </div>
                <div id='ventus_card'>
                    <p>For a PV-value higher than 6 a ventus will be autoselected. This can be turned off later on if the customer does not want a ventus system.</p>
                    <p><img height='200px' src="{% static 'images/ventus.jpg' %}"></p><br>
                </div>
            </div>
        </div>
        {% endif %}

	</div>

</div>


<script type='text/javascript'>

(function($) {
    $(function() {
        var selectField = $('#id_cpp_fpp');
        var oring = $('#id_pressure_oring');


        function toggleVerified(value) {
            if (value == 'fpp') {
            	oring.parent().show();
        	} else {
        		oring.parent().hide();
        	};
        }

        toggleVerified();


        $('#id_fpp_cpp_info').hide();

        $('#id_cpp_fpp_container')
        .mouseover(function() {
            $('#id_fpp_cpp_info').show();
            clearTimeout(hoverTimeOut);
        })
        .mouseout(function() {
            hoverTimeOut = setTimeout(function() {
                $('#id_fpp_cpp_info').hide();
            }, 500);
        })

        $('#id_vgp_info').hide();

        $('#id_vgp_container')
        .mouseover(function() {
            $('#id_vgp_info').show();
            clearTimeout(hoverTimeOut_vgp);
        })
        .mouseout(function() {
            hoverTimeOut_vgp = setTimeout(function() {
                $('#id_vgp_info').hide();
            }, 500);
        })
        
        
    });
})(jQuery);

</script>

<script type='text/javascript'>
(function($) {
    $(function() {
        var selectField = $('#id_application');
        var fwd = $('#id_fwd_seal');
        var aft = $('#id_aft_seal');
        var aftsize = $('#id_aftSize')
        var fwdsize = $('#id_fwdSize')
        var aftbuild = $('#id_aft_build_in_length');
        var linercentering = $('#id_linerCentering_container');

        function toggleVerified(value) {
            value == '1' ? aft.parent().show() : aft.parent().hide();
            value == '1' ? fwd.parent().show() : fwd.parent().hide();
            toggleSizes();
        }

        function toggleSizes() {
            if (aft.is(':checked') || selectField.val() != '1') {
                aftsize.parent().show();
                aftbuild.parent().show();
                linercentering.parent().show();
            } else {
                aftsize.parent().hide(); 
                aftbuild.parent().hide();
                linercentering.parent().hide();
            }

            if (fwd.is(':checked')) {
                fwdsize.parent().show();
            } else {
                fwdsize.parent().hide();
            }
        }




        function checkVentus(PV) {
            if ( $('#id_aftSize').val() > 0 && $('#id_rpm').val() && $('#id_draught_shaft').val() ) {
                PV = $('#id_aftSize').val()*3.14*($('#id_rpm').val()/60)*($('#id_draught_shaft').val()/10000);

                
            } else {
                PV = 0;
            }

            (PV > 6) ? $('#ventus_card').show() : $('#ventus_card').hide();
            (PV > 4) ? $('#fkm_card').show() : $('#fkm_card').hide();
            $('#pv_value').html("The PV-value is equal to " + PV.toFixed(1));
        }


        toggleSizes();
        checkVentus();


        $('#id_aftSize').keyup(function() {
            checkVentus();
        })

        $('#id_rpm').keyup(function() {
            checkVentus();
        })

        $('#id_draught_shaft').keyup(function() {
            checkVentus();
        })

        // show/hide on load based on pervious value of selectField
        toggleVerified(selectField.val());


        aft.change(function() {
            toggleSizes();
        })

        fwd.change(function() {
            toggleSizes();
        })

        // show/hide on change
        selectField.change(function() {
            toggleVerified($(this).val());
        });



        
    });
})(jQuery);

</script>

<script type='text/javascript'>
(function($) {
    $(function() {
        $("#id_company_autocomplete").autocomplete({
            source: "{% url 'sealadvisor2:get_companies' %}",
            selectFirst:true,
            minLength: 1,
        }).focus(function () {
            $(this).autocomplete("search", "");
        });



        

    });

})(jQuery);

</script>

{% endblock %}	 