erp/urls.py
from django.conf.urls import url
from erp import views



app_name = 'erp'



urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^allParts/$', views.viewAllParts, name='viewAllParts'),
	url(r'^allSeals/$', views.viewSeals, name='viewSeals'),
	url(r'^addPart/$', views.addPart, name='addPart'),
	url(r'^editPart/(?P<part_id>\d+)/$', views.editPart, name='editPart'),
	url(r'^addSeal/$', views.addSeal, name='addSeal'),
	url(r'^viewSeal/(?P<seal_id>\d+)/addComponent/$', views.addComponentToSeal, name='addComponentToSeal'),
	url(r'^viewSeal/(?P<seal_id>\d+)/addServiceReport/$', views.addServiceReport, name='addServiceReport'),
	url(r'^downloadServiceReport/(?P<report_id>\d+)/$', views.exportReportAsPDF, name='exportReportAsPDF'),
	url(r'^viewSeal/(?P<seal_id>\d+)/checkComponentChange/(?P<change_id>\d+)/$', views.checkComponentChange, name='checkComponentChange'),
	url(r'^viewSeal/(?P<seal_id>\d+)/$', views.viewSeal, name='viewSeal'),
	url(r'^addCompany/$', views.addCompany, name='addCompany'),
	url(r'^company/(?P<company_id>\d+)/addVessel/$', views.addVessel, name='addVessel'),
	url(r'^addVesselCompany/$', views.addVesselCompany, name='addVesselCompany'),
	url(r'^addMechanic/$', views.addMechanic, name='addMechanic'),
	url(r'^addCategory/$', views.addCategory, name='addCategory'),
	url(r'^addMaterial/$', views.addMaterial, name='addMaterial'),
	url(r'^addContactPerson/$', views.addContactPerson, name='addContactPerson'),
	url(r'^editCompany/(?P<company_id>\d+)/$', views.editCompany, name='editCompany'),
	url(r'^editVessel/(?P<vessel_id>\d+)/$', views.editVessel, name='editVessel'),
	url(r'^editMechanic/(?P<mechanic_id>\d+)/$', views.editMechanic, name='editMechanic'),
	url(r'^editSeal/(?P<seal_id>\d+)/$', views.editSeal, name='editSeal'),
	url(r'^editMaterial/(?P<material_id>\d+)/$', views.editMaterial, name='editMaterial'),
	url(r'^editCategory/(?P<category_id>\d+)/$', views.editCategory, name='editCategory'),
	url(r'^editContactPerson/(?P<contact_id>\d+)/$', views.editContactPerson, name='editContactPerson'),
]

lagersmit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ajax_select import urls as ajax_select_urls


from tastypie.api import Api
from angular.api import JobResource


job_resource = JobResource()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sealadvisor2/', include('sealadvisor2.urls')),
    url(r'^erp/', include('erp.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^isah/', include('isah.urls')),
    url(r'^servicerapportage/', include('servicerapportage.urls')),
    url(r'^api/', include(job_resource.urls)),
]

sealadvisor2/urls.py
from django.conf.urls import url
from sealadvisor2 import views
from erp.models import Company
from ajax_select import urls as ajax_select_urls


app_name = 'sealadvisor2'



urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^supreme/$', views.supreme, name='supreme'),
	url(r'^supreme/chooseSalesType/$', views.salesType, name='supremeSalesType'),
	url(r'^supreme/(?P<supreme_id>\d+)/edit/$', views.supremeEdit, name='supremeEdit'),
	url(r'^supreme/(?P<supreme_id>\d+)/aft/$', views.supremeAft, name='supremeAft'),
	url(r'^supreme/(?P<supreme_id>\d+)/fwd/$', views.supremeFwd, name='supremeFwd'),
	url(r'^supreme/(?P<supreme_id>\d+)/aft/(?P<aft_id>\d+)/edit$', views.supremeAftEdit, name='supremeAftEdit'),
	url(r'^supreme/(?P<supreme_id>\d+)/fwd/(?P<fwd_id>\d+)/edit$', views.supremeFwdEdit, name='supremeFwdEdit'),
	url(r'^supreme/(?P<supreme_id>\d+)/environment/$', views.supremeEnvironment, name='supremeEnvironment'),
	url(r'^supreme/(?P<supreme_id>\d+)/environment/(?P<env_id>\d+)/edit$', views.supremeEnvironmentEdit, name='supremeEnvironmentEdit'),
	url(r'^supreme/(?P<supreme_id>\d+)/overview/$', views.supremeOverview, name='supremeOverview'),
	url(r'^addcompany/$', views.CompanyCreate.as_view(), name="createCompany"),
	url(r'^updatecompany/(?P<pk>\d+)$', views.CompanyUpdate.as_view(success_url='/sealadvisor2/'), name="updateCompany"),
	url(r'^deletecompany/(?P<pk>\d+)$', views.CompanyDelete.as_view(success_url='/sealadvisor2/'), name="deleteCompany"),
	url(r'^deleteadvise/(?P<pk>\d+)$', views.AdviseDelete.as_view(success_url='/sealadvisor2/advises/'), name="deleteAdvise"),
	url(r'^companies/$', views.Companies, name='companies'),
	url(r'^advises/$', views.SupremeAdvises, name='advises'),
	url(r'^addtypeapproval/$', views.TypeApprovalCreate.as_view(success_url='/sealadvisor2/typeapprovals/'), name="createTypeApproval"),
	url(r'^updatetypeapproval/(?P<pk>\d+)$', views.TypeApprovalUpdate.as_view(success_url='/sealadvisor2/typeapprovals/'), name="updateTypeApproval"),
	url(r'^deletetypeapproval/(?P<pk>\d+)$', views.TypeApprovalDelete.as_view(success_url='/sealadvisor2/typeapprovals/'), name="deleteTypeApproval"),
	url(r'^typeapprovals/$', views.TypeApprovalOverview, name='typeApprovalOverview'),
	url(r'^addclass/$', views.ClassCreate.as_view(success_url='/sealadvisor2/class/'), name="createClass"),
	url(r'^updateclass/(?P<pk>\d+)$', views.ClassUpdate.as_view(success_url='/sealadvisor2/class/'), name="updateClass"),
	url(r'^deleteclass/(?P<pk>\d+)$', views.ClassDelete.as_view(success_url='/sealadvisor2/class/'), name="deleteClass"),
	url(r'^class/$', views.ClassOverview, name='classOverview'),
	#api urls
	url(r'^get_companies/$', views.get_companies, name='get_companies'),
	url(r'^companyEdit2/(?P<company_id>\d+)/$', views.CompanyDefaultsEdit, name='CompanyEdit2'),


]

erp/forms.py
from django import forms
from erp.models import Seal, Company, Part, sealComponent, serviceReport, confirmComponentChange, Vessel, Mechanic, partMaterial, partCategory, contactPerson



class selectCompany(forms.Form):
	company = forms.ModelChoiceField(queryset=Company.objects.all())



class addSealForm(forms.ModelForm):
	class Meta:
		model = Seal
		fields = ('seal_type','x_number', 'date_installed', 'company', 'size','vessel')

class addCompanyForm(forms.ModelForm):
	class Meta:
		model = Company
		fields = ('name',)

class addContactPersonForm(forms.ModelForm):
	class Meta:
		model = contactPerson
		fields = ('first_name','last_name','company','position')

class addMaterialForm(forms.ModelForm):
	class Meta:
		model = partMaterial
		fields = ('name',)

class addCategoryForm(forms.ModelForm):
	class Meta:
		model = partCategory
		fields = ('name',)

class addMechanicForm(forms.ModelForm):
	class Meta:
		model = Mechanic
		fields = ('first_name','last_name')

class addVesselForm(forms.ModelForm):
	def __init__(self,*args,**kwargs):
		self.company_id = kwargs.pop('company_id')
		super(addVesselForm, self).__init__(*args,**kwargs)
		self.fields['contacts'].queryset = contactPerson.objects.filter(company=self.company_id)


	class Meta:
		model = Vessel
		fields = ('name','imo','company','contacts')


class addPartForm(forms.ModelForm):
	class Meta:
		model = Part
		fields = ('number','category','size','name','description','material')


class addComponentToSealForm(forms.ModelForm):

	def __init__(self,*args,**kwargs):
		self.size = kwargs.pop('size')
		super(addComponentToSealForm, self).__init__(*args,**kwargs)
		self.fields['part'].queryset = Part.objects.filter(size=self.size)


	class Meta:
		model = sealComponent
		fields = ('number','part','status')


class addServiceReportForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.seal_id = kwargs.pop('seal_id')
		super(addServiceReportForm, self).__init__(*args,**kwargs)
		self.fields['parts_to_replace'].queryset = sealComponent.objects.filter(seal=self.seal_id)

	class Meta:
		model = serviceReport
		fields = ('date','location','reason', 'mechanics','superintendant', 'parts_to_replace')



class confirmComponentChangeForm(forms.ModelForm):

	class Meta:
		model = confirmComponentChange
		fields = ('old_part', 'new_part', 'confirm')

erp/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response, HttpResponseRedirect
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from erp.tables import componentTable, partsTable, sealTable
from datetime import datetime

# Create your views here.

from erp.models import Seal, Company, sealComponent, Part, serviceReport, sealComponent, confirmComponentChange, Vessel, Mechanic, partMaterial, partCategory, contactPerson
from erp import forms

def index(request):
	seals = Seal.objects.all()
	companies = Company.objects.all()
	vessels = Vessel.objects.all()
	mechanics = Mechanic.objects.all()
	categories = partCategory.objects.all()
	materials = partMaterial.objects.all()
	contacts = contactPerson.objects.all()

	return render(request, 'erp/index.html', {'seals':seals, 'companies':companies,'vessels':vessels, 'mechanics':mechanics, 'categories':categories,'materials':materials, 'contacts':contacts })



def viewAllParts(request):
	parts = Part.objects.all()

	table = partsTable(parts)

	return render(request, 'erp/viewAllParts.html', {'table':table})


def viewSeals(request):
    seals = Seal.objects.all()
    
    table = sealTable(seals)
    
    return render(request, 'erp/viewSeals.html', {"table": table})


def addPart(request):

	if request.method == "POST":
		form = forms.addPartForm(request.POST)

		if form.is_valid():
			newPart = form.save()

			return redirect('erp:viewAllParts')
	else:
		form = forms.addPartForm()

	return render(request,'erp/simple_form.html', {'form':form,'title':'Add part', 'submit':'Create part'})


def editPart(request, part_id):
	part = get_object_or_404(Part, pk=part_id)

	if request.method == "POST":
		form = forms.addPartForm(request.POST, instance=part)

		if form.is_valid():
			newPart = form.save()

			return redirect('erp:viewAllParts')
	else:
		form = forms.addPartForm(initial={'number':part.number,'category':part.category.id,'size':part.size,'name':part.name,'description':part.description,'material':part.material.id})

	return render(request,'erp/simple_form.html', {'form':form,'title':'Edit part', 'submit':'Save part'})




def viewSeal(request, seal_id):
	seal = get_object_or_404(Seal, pk=seal_id)
	parts = sealComponent.objects.filter(seal_id=seal_id)
	reports = serviceReport.objects.filter(seal_id=seal_id)
	table = componentTable(parts)
	changed_parts = confirmComponentChange.objects.filter(seal_id=seal_id)



	return render(request, 'erp/viewSeal.html', {'seal':seal, 'parts':parts, 'table': table, 'reports':reports, 'changes': changed_parts })



def addSeal(request):

	if request.method=='POST':
		form = forms.addSealForm(request.POST)

		if form.is_valid():
			newSeal = form.save()

			return redirect('erp:index')

	else:
		form = forms.addSealForm()

	return render(request, 'erp/seal.html', {'form':form, 'submit':'Create new seal object','title':'Add new seal'})



def editSeal(request, seal_id):
	seal = get_object_or_404(Seal, pk=seal_id)
	old = seal

	if request.method=='POST':
		form = forms.addSealForm(request.POST, instance = seal)

		if form.is_valid():
			s = form.save()
			return redirect('erp:viewSeal', seal_id)

	else:
		form = forms.addSealForm(initial={'date_installed':seal.date_installed, 'x_number':seal.x_number, 'size':seal.size,'company':seal.company.id,'seal_type':seal.seal_type, 'vessel': seal.vessel.id})

	return render(request, 'erp/seal.html', {'form':form, 'submit':'Save seal','title':'Edit seal'})


def addComponentToSeal(request, seal_id):
	seal = get_object_or_404(Seal, pk=seal_id)
	size = seal.size

	if request.method == 'POST':
		form = forms.addComponentToSealForm(request.POST,size=size)

		if form.is_valid():
			newComponent = form.save(commit=False)
			newComponent.seal = seal
			newComponent.save()

			return redirect('erp:viewSeal', seal_id)

	else:
		form = forms.addComponentToSealForm(size=size)

	return render(request, 'erp/simple_form.html', {'form':form, 'submit':'Add component to seal','title':'Add component'})



def addCompany(request):
	if request.method=="POST":
		form = forms.addCompanyForm(request.POST)

		if form.is_valid():
			newCompany = form.save()

			return redirect('erp:index')

	else:
		form = forms.addCompanyForm()

	return render(request, 'erp/company.html', {'form': form, 'submit':'Create new company', 'title':'Add new company'})


def editCompany(request, company_id):
	company = get_object_or_404(Company, pk=company_id)

	if request.method == 'POST':
		form = forms.addCompanyForm(request.POST, instance = company)

		if form.is_valid():
			form.save()

			return redirect('erp:index')

	else:
		form = forms.addCompanyForm(initial={'name':company.name })

	return render(request, 'erp/company.html', {'form':form,'submit':'Save company','title':'Edit company'})


def addVessel(request, company_id):
	if request.method=="POST":
		form = forms.addVesselForm(request.POST, company_id=company_id)

		if form.is_valid():
			newVessel = form.save()

			return redirect('erp:index')

	else:
		form = forms.addVesselForm(company_id=company_id, initial={'company': company_id })

	return render(request, 'erp/simple_form.html', {'form': form, 'submit':'Create new vessel', 'title':'Add vessel'})


def editVessel(request, vessel_id):
	vessel = get_object_or_404(Vessel, pk=vessel_id)

	if request.method == 'POST':
		form = forms.addVesselForm(request.POST, company_id = vessel.company.id, instance = vessel)

		if form.is_valid():
			form.save()

			return redirect('erp:index')

	else:
		form = forms.addVesselForm(company_id=vessel.company.id, initial={'name':vessel.name, 'company':vessel.company.id, 'imo': vessel.imo, 'contacts':[contact.id for contact in vessel.contacts.all()] })

	return render(request, 'erp/simple_form.html', {'form':form,'submit':'Save vessel','title':'Edit vessel'})



def addContactPerson(request):
	if request.method=="POST":
		form = forms.addContactPersonForm(request.POST)

		if form.is_valid():
			newContactPerson = form.save()

			return redirect('erp:index')

	else:
		form = forms.addContactPersonForm()

	return render(request, 'erp/simple_form.html', {'form': form, 'submit':'Create new contact person', 'title':'Add contact person'})


def editContactPerson(request, contact_id):
	contact = get_object_or_404(contactPerson, pk=contact_id)

	if request.method == 'POST':
		form = forms.addContactPersonForm(request.POST, instance = contact)

		if form.is_valid():
			form.save()

			return redirect('erp:index')

	else:
		form = forms.addContactPersonForm(initial={'first_name':contact.first_name, 'last_name':contact.last_name,'position':contact.position, 'company':contact.company.id })

	return render(request, 'erp/simple_form.html', {'form':form,'submit':'Save contact','title':'Edit contact'})



def addServiceReport(request, seal_id):
	seal = get_object_or_404(Seal, pk=seal_id)

	if request.method == "POST":
		form = forms.addServiceReportForm(request.POST, seal_id=seal_id)

		if form.is_valid():
			newServiceReport = form.save(commit=False)
			newServiceReport.seal = seal
			newServiceReport.save()
			form.save_m2m()

			servicereport = get_object_or_404(serviceReport, pk=newServiceReport.id)


			# create confirm objects for each changed part
			# for change in servicereport.parts_to_replace.all():
			# 	confirmComponentChange.objects.create(report=servicereport, old_part=change.part, new_part=change.part)

			return redirect('erp:viewSeal', seal_id)

	else:
		form = forms.addServiceReportForm(seal_id=seal_id)


	return render(request, 'erp/simple_form.html', {'form':form, 'title':'Add service report for '+seal.x_number,'submit':'Add report', 'seal':seal})


def checkComponentChange(request,seal_id, change_id):

	change = get_object_or_404(confirmComponentChangeForm, pk = change_id)

	if request.method == "POST":
		form = forms.confirmComponentChangeForm(request.POST, instance=change)

		if form.is_valid():
			form.save(update_fields=["name"])

			return redirect('erp:viewSeal', seal_id)

	form = forms.confirmComponentChangeForm(initial = {'old_part':change.old_part, 'new_part': change.new_part})

	return render(request,'erp/simple_form.html', {'form':form, 'title':'Check part replacement','submit':'Save'})



def addMechanic(request):
	if request.method=="POST":
		form = forms.addMechanicForm(request.POST)

		if form.is_valid():
			newMechanic = form.save()

			return redirect('erp:index')

	else:
		form = forms.addMechanicForm()

	return render(request, 'erp/simple_form.html', {'form': form, 'submit':'Create new mechanic', 'title':'Add mechanic'})


def editMechanic(request, mechanic_id):
	mechanic = get_object_or_404(Mechanic, pk=mechanic_id)

	if request.method == 'POST':
		form = forms.addMechanicForm(request.POST, instance = mechanic)

		if form.is_valid():
			form.save()

			return redirect('erp:index')

	else:
		form = forms.addMechanicForm(initial={'first_name':mechanic.first_name, 'last_name': mechanic.last_name })

	return render(request, 'erp/simple_form.html', {'form':form,'submit':'Save mechanic','title':'Edit mechanic'})


def addMaterial(request):
	if request.method=="POST":
		form = forms.addMaterialForm(request.POST)

		if form.is_valid():
			newMaterial = form.save()

			return redirect('erp:index')

	else:
		form = forms.addMaterialForm()

	return render(request, 'erp/simple_form.html', {'form': form, 'submit':'Create new material', 'title':'Add material'})

def editMaterial(request, material_id):
	material = get_object_or_404(partMaterial, pk=material_id)

	if request.method == 'POST':
		form = forms.addMaterialForm(request.POST, instance = material)

		if form.is_valid():
			form.save()

			return redirect('erp:index')

	else:
		form = forms.addMaterialForm(initial={'name':material.name })

	return render(request, 'erp/simple_form.html', {'form':form,'submit':'Save material','title':'Edit material'})





def addCategory(request):
	if request.method=="POST":
		form = forms.addCategoryForm(request.POST)

		if form.is_valid():

erp/templates/erp/base.html
{% load staticfiles %}
<html>
	<head>
		<style>

		</style>
		<!--Import materialize.css-->

        {% include 'material/includes/material_css.html' %}
        <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
        {% include 'material/includes/material_js.html' %}
        {% load material_form %} 
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/sealadvisor2.css' %}">
	</head>
  
 	<body>
 	
        <div id='background'></div>
            
        
        <nav>
            <div class="nav-wrapper blue lighten-4">
            <a href="#" class="brand-logo"><img src="{% static 'images/logo-lagersmit.png' %}"></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'erp:index' %}">Home</a></li>
                <li><a href="{% url 'sealadvisor2:companies' %}">Companies</a></li>
                <li><a href="{% url 'erp:viewSeals' %}">Seals</a></li>
            </ul>
            </div>
        </nav>

        <div class="content container">
                {% block content %}
                {% endblock %}
        </div>

 	</body>
</html>

erp/templates/erp/index.html
{% extends 'erp/base.html' %}
{% load static %}


{% block content %}
<h1>ERP</h1>

<div class='row'>
  <div class='col s6'>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Seals</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addSeal' %}"><i class="material-icons">add</i></a>
        </div>
        {% for seal in seals %}
        <p><a href="{% url 'erp:viewSeal' seal.id %}">{{ seal.x_number }}</a> - <a href="{% url 'erp:editSeal' seal.id %}">edit</a> - <a href="{% url 'erp:addServiceReport' seal.id %}">Add service report</a></p>
        {% endfor %}
      </div>
    </div>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Companies</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addCompany' %}"><i class="material-icons">add</i></a>
        </div>
        {% for company in companies %}
        <p>{{ company }} - <a href="{% url 'erp:editCompany' company.id %}">edit</a></p>
        {% endfor %}
      </div>
    </div>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Part categories</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addCategory' %}"><i class="material-icons">add</i></a>
        </div>
        {% for category in categories %}
        <p>{{ category }} - <a href="{% url 'erp:editCategory' category.id %}">edit</a></p>
        {% endfor %}
      </div>
    </div>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Part materials</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addMaterial' %}"><i class="material-icons">add</i></a>
        </div>
        {% for material in materials %}
        <p>{{ material }} - <a href="{% url 'erp:editMaterial' material.id %}">edit</a></p>
        {% endfor %}
      </div>
    </div>

  </div>
  <div class='col s6'>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Parts</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addPart' %}"><i class="material-icons">add</i></a>
        </div>
        <p><a href="{% url 'erp:viewAllParts' %}">View all parts</a></p>
      </div>
    </div>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Vessels</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addVesselCompany' %}"><i class="material-icons">add</i></a>
        </div>
        {% for vessel in vessels %}
        <p>{{ vessel }}, {{ vessel.company }}, {{ vessel.imo }} - <a href="{% url 'erp:editVessel' vessel.id %}">edit</a></p>
        {% endfor %}
      </div>
    </div>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Mechanics</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addMechanic' %}"><i class="material-icons">add</i></a>
        </div>
        {% for mechanic in mechanics %}
        <p>{{ mechanic }} - <a href="{% url 'erp:editMechanic' mechanic.id %}">edit</a></p>
        {% endfor %}
      </div>
    </div>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Contact persons</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addContactPerson' %}"><i class="material-icons">add</i></a>
        </div>
        {% for contact in contacts %}
        <p>{{ contact }}, {{ contact.company }}, {{ contact.position }} - <a href="{% url 'erp:editContactPerson' contact.id %}">edit</a></p>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red" href="{% url 'erp:addSeal' %}">
      <i class="large material-icons">add</i>
    </a>
    <ul>
      <li><a href="{% url 'erp:addCompany' %}" class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
      <!--<li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
      <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>-->
    </ul>
  </div>
{% endblock %}	 

erp/templates/erp/viewSeal.html
{% extends 'erp/base.html' %}
{% load render_table from django_tables2 %}
{% load static %}


{% block content %}
<h1>{{ seal.x_number }}</h1>

<p><a class='btn waves-effect waves-light blue' href="{% url 'erp:index' %}">Home</a></p>
<br>

<div class='row'>
  <div class='col s6'>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Seal information</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:editSeal' seal.id %}"><i class="material-icons">edit</i></a>
        </div>
        <p>X number: {{ seal.x_number }}</p>
        <p>Type: {{ seal.seal_type }}</p>
        <p>Company: {{ seal.company }}</p>
        <p>Vessel: {{ seal.vessel }}</p>
        <p>Installed: {{ seal.date_installed }}</p>

        {% if seal.vessel.contacts %}
        <p><br><b>Contacts</b></p>
        {% for contact in seal.vessel.contacts.all %}
        <p>{{ contact }}</p>
        {% endfor %}
        {% endif %}
      </div>
    </div>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Service reports</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addServiceReport' seal.id %}"><i class="material-icons">add</i></a>
        </div>
        <ul class='collection'>
        {% for report in reports %}
          <li class='collection-item'>Name: {{ report }} - <a href="{% url 'erp:exportReportAsPDF' report.id %}">download report</a><br>
           Parts to replace: {% for part in report.parts_to_replace.all %}{{ part }},{% endfor %}</li>
        {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class='col s6'>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Parts</span>
        <div style='float:right;'>
          <a class="btn-floating waves-effect waves-light blue" href="{% url 'erp:addComponentToSeal' seal.id %}"><i class="material-icons">add</i></a>
        </div>
        {% render_table table %}
      </div>
    </div>
    <div class='card teal lighten-4'>
      <div class='card-content'>
        <span class='card-title black-text'>Confirm replacement parts</span>
        {% for change in changes %}
        <p>Old: {{ change.old_part }} - New: {{ change.new_part }}</p>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


{% endblock %}	 